require "erb"


module Enumerable
  def foldr(state, &block)
    reverse.inject(state) { |state, x| block.call(x, state) }
  end

  alias_method(:foldl, :inject)
end

def comma(xs)
  xs.map(&", ".method(:+))
end

def typename(xs)
  xs.map(&"typename ".method(:+))
end

def apply
  -> (f, *args) {
    "typename #{f}::type::template apply<#{args.join(', ')}>"
  }
end


task :default => [:all]
task :all

def generate_erb(input, output)
  task :all => [output]

  file output => [input] do |task|
    erb = ERB.new(File.read(input), nil, '-')
    erb.filename = input

    File.open(output, 'w') do |out|
      out.write(erb.result)
    end
  end
end


["bounded", "variadic", "variadic_aliased", "until"].each do |fold|
  generate_erb("left_folds/#{fold}.erb.hpp", "../include/boost/mpl11/detail/left_folds/#{fold}.hpp")
end

["variadic"].each do |fold|
  generate_erb("right_folds/#{fold}.erb.hpp", "../include/boost/mpl11/detail/right_folds/#{fold}.hpp")
end

generate_erb("test_foldl.erb.hpp", "../include/boost/mpl11/detail/test/foldl.hpp")
generate_erb("test_foldr.erb.hpp", "../include/boost/mpl11/detail/test/foldr.hpp")
generate_erb("test_logical_or.erb.hpp", "../include/boost/mpl11/detail/test/logical_or.hpp")
